In [ ]:
import numpy as np
# Q1
arr1 = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr1)
arr_add = arr1 + 2
print("After adding 2:", arr_add)

arr_mult = arr1 * 3
print("After multiplying by 3:", arr_mult)

arr_div = arr1 / 2
print("After dividing by 2:", arr_div)


Original Array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [ ]:
import numpy as np
# Q2
arr2 = np.array([1, 2, 3, 6, 4, 5])
arr_rev = arr2[::-1]
print("Reversed array:", arr_rev)

def most_frequent(arr):
    vals, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_val = vals[np.argmax(counts)]
    indices = np.where(arr == most_freq_val)[0]
    return most_freq_val, indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

val_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {val_x}, Indices: {indices_x}")

val_y, indices_y = most_frequent(y)
print(f"Most frequent value in y: {val_y}, Indices: {indices_y}")

Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [ ]:
import numpy as np
# Q3
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at 1st row, 2nd column:", arr3[0, 1])
print("Element at 3rd row, 1st column:", arr3[2, 0])

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [3]:
#Question4
ShikharSaxena = np.linspace(10, 100, 25)
print("Original Array:\n", ShikharSaxena)
print("\nArray Properties:")
print(f"Dimensions: {ShikharSaxena.ndim}")
print(f"Shape: {ShikharSaxena.shape}")
print(f"Total elements: {ShikharSaxena.size}")
print(f"Data type: {ShikharSaxena.dtype}")
print(f"Total bytes consumed: {ShikharSaxena.nbytes}")
transposed_array = ShikharSaxena.reshape(25, 1)
print("\nTransposed array using reshape():\n", transposed_array)
print("\nUsing T attribute:\n", ShikharSaxena.T)

Original Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Array Properties:
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [4]:
ucs420_ShikharSaxena = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])
mean_value = np.mean(ucs420_ShikharSaxena)
median_value = np.median(ucs420_ShikharSaxena)
max_value = np.max(ucs420_ShikharSaxena)
min_value = np.min(ucs420_ShikharSaxena)
unique_elements = np.unique(ucs420_ShikharSaxena)
reshaped_ucs420_ShikharSaxena = ucs420_ShikharSaxena.reshape(4, 3)
resized_ucs420_ShikharSaxena = np.resize(ucs420_ShikharSaxena, (2, 3))
print("Original 2D Array (3x4):\n", ucs420_ShikharSaxena)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_ShikharSaxena)
print("\nResized Array (2x3):\n", resized_ucs420_ShikharSaxena)

Original 2D Array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
